x-service: &default-service
  image: golang:1.20
  working_dir: /app
  network_mode: "host"
  volumes:
    - ../.:/app
    - /tmp/go-cache:/go
    - /tmp/go-build-cache:/root/.cache/go-build
services:
  build-once:
    <<: *default-service
    profiles:
      - build-once
    command: /bin/bash -c "git config --global --add safe.directory '*' && make -B all"
  indexer:
    <<: *default-service
    command: go run ./cmd/exporter -config /app/local_deployment/config.yml
    environment:
      - INDEXER_ENABLED=true
  eth1indexer:
    <<: *default-service
    command: go run ./cmd/eth1indexer -config /app/local_deployment/config.yml -blocks.concurrency 1 -blocks.tracemode 'geth' -data.concurrency 1 --balances.enabled
  rewards-exporter:
    <<: *default-service
    command: go run ./cmd/rewards_exporter -config /app/local_deployment/config.yml
  statistics:
    <<: *default-service
    command: go run ./cmd/statistics -config /app/local_deployment/config.yml --charts.enabled --graffiti.enabled -validators.enabled
  # frontend-data-updater:
  #   <<: *default-service
  #   command: go run ./cmd/frontend-data-updater -config /app/local_deployment/config.yml
  frontend:
    image: ghcr.io/gobitfly/beaconchain_frontend:main
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_CLIENT="http://172.17.0.1:8080/api/i/"
      - NUXT_PUBLIC_LEGACY_API_CLIENT="http://172.17.0.1:8080/"
      - NUXT_PRIVATE_API_SERVER="http://172.17.0.1:8080/api/i/"
      - NUXT_PRIVATE_LEGACY_API_SERVER="http://172.17.0.1:8080/"
      - NUXT_PUBLIC_API_KEY="xxx"
      - NUXT_PUBLIC_X_USER_ID=1
